### ISSUE TITLE
unloadAll destroys records and an assertion fails in flushCanonical

### ISSUE THREAD

**Issue by givanse** [emberjs/data#2982]
I have a couple of acceptance tests that pass if run by themselves, but fail when all the tests are executed together. The error:

    beforeEach failed on visiting / second time: Assertion Failed: Cannot call get with 'isDeleted' on an undefined object.

The failure happens at a portion of code that was added by this bug fix: https://github.com/bmac/data/commit/c54323b15c49588123c42e9d504afcbd85a9a529

What is happening in my tests is that when the application is destroyed `unloadAll()` is being called and each record is being deleted like this:

    record.unloadRecord()
    record.destroy()

So, when we reach `flushCanonical` in this line:

    return !record.get('isDeleted');

The assertion fails because the record doesn't have the `isDelete` property, but it has set to true `isDestroyed` and `isDestroying`.

Currently I have a workaround/hack that allows all the tests to pass:

    afterEach: function() {
      var store = application.registry.lookup('store:main');
      Ember.run(function() {
        var records = store.all('someModel');
        records.forEach(function(record) {
          store.unloadRecord(record);
        });
      });
      Ember.run(application, 'destroy');
    }

**Comment by givanse** [comment]
I tried to build a test case (I wanted to submit a PR), but I haven't been able to reproduce the problem without creating and destroying an entire application...

I prepared a branch from my project where the issue reproduces with a minimal set of data.

    git clone -b test-case git@github.com:givanse/mvc-tree.git

In file ` mvc-tree/tests/acceptance/index-test.js` you can see the assertion failure if you remove the workaround.

**Comment by igorT** [comment]
Hi, thanks for reporting the issue. I am having trouble running your test case, when I do ember serve in the repo after npm&bower install I get 
```
➜  mvc-tree git:(test-case) ember serve

Missing npm packages:
Package: ember-data
  * Specified: components/ember#canary
  * Installed: (not installed)

Run `npm install` to install missing dependencies.
```

**Comment by givanse** [comment]
Sorry about that, I just fixed the branch.

    git pull origin test-case

Probably not relevant, but I'll mention that the data is being preloaded from an initializer: https://github.com/givanse/mvc-tree/blob/test-case/app/initializers/preload-data.js

**Comment by givanse** [comment]
The test http://localhost:4200/tests?nocontainer&hidepassed&module=Acceptance%3A%20Index
file `mvc-tree/tests/acceptance/index-test.js`

**Comment by piotrpalek** [comment]
I encountered an error when unloading records as well and managed to distrill it into a jsbin: http://emberjs.jsbin.com/mazopeburo/2/edit

**Comment by pangratz** [comment]
@piotrpalek awesome JSBin to demonstrate the issue. I updated ember-data to use the [`references` branch](https://github.com/emberjs/data/tree/0ef340fb6eb95e08568c67135f952894eba03c2d) and then the bug is gone ... http://emberjs.jsbin.com/xutopohevu/1/edit?js,console,output

**Comment by piotrpalek** [comment]
Np :) @pangratz you sure about that? I click "unload post" then "refresh" and still get `Error: Assertion Failed: calling set on destroyed object...` in your jsbin.

**Comment by pangratz** [comment]
Oh boy, I guess I didn't look to closely :cry: Sorry for the false alarm

**Comment by igorT** [comment]
I think this might be solved on master, can you check please?

**Comment by sly7-7** [comment]
@igorT If it's the same as https://github.com/emberjs/data/issues/3084, then I doubt it's resolved

**Comment by givanse** [comment]
I just took master for a spin and it *seems* like the `flushCanonical` problem is solved, but something else popped up. I'm still digging, but I'll share the new error in case I'm missing something obvious.

```js
Error: Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of mvc-tree@model:column:
```

**Comment by givanse** [comment]
Waiting for https://github.com/emberjs/data/issues/3192

**Comment by igorT** [comment]
I believe this was fixed as #3192 is closed. Please reopen if it still an issue
