### ISSUE TITLE
Deprecation warning for lookupSerializer not working

### ISSUE THREAD

**Issue by phammers** [emberjs/data#4784]
I tried upgrading our application to 2.11.0.  Getting this deprecation warning in the console

`When calling `Ember.deprecate` you must provide an `options` hash as the third parameter.  `options` should include `id` and `until` properties. [deprecation id: ember-debug.deprecate-options-missing] `

I traced it back to this deprecation not logging properly:

`Use of lookupSerializer is deprecated, use serializerFor instead.`

**Comment by runspired** [comment]
@phammers thanks!

**Comment by runspired** [comment]
It looks as though I already fixed this on master, I'll backport a fix to 2.11 (and 2.12 if needed)

**Comment by bmac** [comment]
I have cherry-picked https://github.com/emberjs/data/commit/0c26d2df8c1baf7cb5099c3fe5ae90d1feade681 to the `beta` and `release` branches so the fix will be included in the next release for 2.11 and 2.12-beta.

**Comment by bmac** [comment]
Ember Data 2.11.1 and 2.12.0-beta.3 have been published with the fix for this issue. I'm going to clise this but let me know if you are still experiencing a problem.

**Comment by JeskTop** [comment]
I update `ember-data` version to `2.11.1`, but still have this problem. @bmac

**Comment by pangratz** [comment]
@JeskTop I can't reproduce this using `2.11.1` in an [ember-twiddle](https://ember-twiddle.com/7c7b64faa47fb6fa058dafc9aef14e52?fileTreeShown=false&openFiles=routes.application.js%2C=). The warning about the misused `Ember.deprecate` is gone - if I change ember data to `v2.11.0` it is logged in the console.

**Comment by JeskTop** [comment]
@phammers Thanks. I already found this problem came frome `ember-data-model-fragments`.
